[package]
name = "sui_broker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dirs = { version = "=4.0.0" }
sui-sdk = { git = "https://github.com/MystenLabs/sui", rev = "df05544fb0cbd6d6db016e71e5facb5e7cc27988" }
tokio = { version = "=1.21.1", features = ["rt"] }
